services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: payoongrak_backend
    ports:
      - "13000:13000"
    environment:
      - NODE_ENV=development
      - PORT=13000
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
    mem_limit: 256m
    mem_reservation: 128m
    cpus: 0.1


